# Generated by Django 3.0.3 on 2020-08-27 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('timestamp', models.TimeField()),
                ('latest_timestamp', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fires_pics')),
                ('cause', models.CharField(choices=[('LIGHTNING', 'lightning'), ('MANMADE', 'man-made'), ('UNKOWN', 'unknown')], default='unknown', max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('long_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('probability', models.CharField(choices=[('VERY HIGH', 'very high'), ('HIGH', 'high'), ('MEDIUM', 'medium'), ('LOW', 'low'), ('UNKOWN', 'unknown')], default='unknown', max_length=10)),
                ('anomaly_arr', models.BinaryField()),
                ('cluster_lst', models.BinaryField()),
                ('px_idx_x', models.IntegerField(default=0)),
                ('px_idx_y', models.IntegerField(default=0)),
            ],
        ),
    ]
