# Generated by Django 3.0.3 on 2020-08-04 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('timestamp', models.TimeField()),
                ('image', models.ImageField(upload_to='')),
                ('cause', models.CharField(choices=[('LIGHTNING', 'lightning'), ('MANMADE', 'man-made'), ('UNKOWN', 'unknown')], default='unknown', max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('long_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
