# Generated by Django 3.0.3 on 2020-08-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200827_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firemodel',
            old_name='actual_14_pts',
            new_name='actual_14_graph_pts',
        ),
        migrations.RenameField(
            model_name='firemodel',
            old_name='actual_7_pts',
            new_name='actual_7_graph_pts',
        ),
    ]
