# Generated by Django 3.0.3 on 2020-08-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200804_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fires'),
        ),
    ]
