# Generated by Django 3.0.3 on 2020-08-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200827_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='firemodel',
            name='diff_graph_pts',
            field=models.BinaryField(default=b'gARdlC4='),
        ),
    ]
