# Generated by Django 3.0.3 on 2020-08-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_firemodel_diff_graph_pts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firemodel',
            name='latest_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='firemodel',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
