# Generated by Django 3.0.3 on 2020-08-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200804_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='firemodel',
            name='probability',
            field=models.CharField(choices=[('VERY HIGH', 'very high'), ('HIGH', 'high'), ('MEDIUM', 'medium'), ('LOW', 'low'), ('UNKOWN', 'unknown')], default='unknown', max_length=10),
        ),
    ]
