# Generated by Django 3.0.3 on 2020-08-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_firemodel_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firemodel',
            name='fire_id',
            field=models.IntegerField(unique=True),
        ),
    ]
