# Generated by Django 3.0.3 on 2020-09-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200902_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firemodel',
            name='lightning_lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='firemodel',
            name='lightning_lon',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='firemodel',
            name='lightning_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
