# Generated by Django 3.0.3 on 2020-08-04 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200804_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firemodel',
            name='fire_id',
        ),
    ]
