# Generated by Django 3.0.3 on 2020-09-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200902_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firemodel',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='fires_gifs'),
        ),
    ]
