# Generated by Django 3.0.3 on 2020-09-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200902_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='firemodel',
            name='vmax',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firemodel',
            name='vmin',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firemodel',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
