# Generated by Django 3.0.3 on 2020-09-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200903_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='firemodel',
            name='jpg_folder_path',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='firemodel',
            name='vmax',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='firemodel',
            name='vmin',
            field=models.FloatField(default=0),
        ),
    ]
